### ISSUE TITLE
Issue with Application

### ISSUE THREAD

**Issue by JeremyHutchings** [barrett777/Heroes.ReplayParser#10]
Hello there,

I was just experimenting with the parser and some local replays I have, and ended up getting an error. Was wondering if you could give me any insight into it please ? 

Thanks
Jeremy

![parser issue](https://cloud.githubusercontent.com/assets/439559/11508876/d5212186-980f-11e5-854e-25515c57f5c9.png)

![console](https://cloud.githubusercontent.com/assets/439559/11508881/dadd0c34-980f-11e5-9bb4-5ba85966e705.png)

**Comment by barrett777** [comment]
Are you using the current version of the parser?  This error can happen if
you are parsing a new replay file with an older version of the replay
parser.

If not, could you email me the replay file to admin@hotslogs.com?

**Comment by JeremyHutchings** [comment]
Thanks, will do. It's the latest code out of GH.

**Comment by barrett777** [comment]
I was able to parse the 3 replays you sent me; are you sure you are using my current master branch?

At the top of that file you should find this line if it is the current version:

// Referenced from https://raw.githubusercontent.com/Blizzard/s2protocol/master/protocol38215.py (Void Beta)

**Comment by barrett777** [comment]
Well I'm going to close this, let me know if it is still a problem

**Comment by JeremyHutchings** [comment]
Yes, we still have issues now it's an index out of range.

![index_out_of_range](https://cloud.githubusercontent.com/assets/439559/11644006/20a55950-9cfd-11e5-8294-8d1f04dd8e91.png)

I grabbed a replay from : http://eu.ets.gg/replays

Team Liquid HotS    Fnatic HotS Enter The Storm EU 4 (EU Qualifier # 3) 5. Dec 2015

**Comment by barrett777** [comment]
There were 3 replays with the title you linked, but I was able to parse them all successfully

Are you using the sample console application I supplied?  You do need to parse the contained files in a specific order, which the console application follows.

If you are not using the console application, and just parsing ReplayGameEvents, the 'replay.ClientList' list will be empty as player data comes from a different file.

If you are using the sample console application, I really think you might be using an older version

Unfortunately the exception in your screenshot covers up a version number.  In your screenshot, can you check the comment that starts with:

"// Referenced from https://raw.github....."

If it's the current version it should be: "Referenced from https://raw.githubusercontent.com/Blizzard/s2protocol/master/protocol38215.py (Void Beta)"

**Comment by JeremyHutchings** [comment]
Syncing up with the latest from master branch I get this : 

![fresh_hots](https://cloud.githubusercontent.com/assets/439559/11829741/b5975cf0-a353-11e5-9a15-33b3ee26bbd8.png)

```
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities.Sync\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\Users\Jeremy\Documents\GitHub\Heroes.ReplayParser\Heroes.ReplayParser.ConsoleApplication\ConsoleApplication1\bin\Debug\ConsoleApplication1.vshost.exe'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x2394 has exited with code 0 (0x0).
The thread 0x2398 has exited with code 0 (0x0).
The thread 0x238c has exited with code 0 (0x0).
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\Users\Jeremy\Documents\GitHub\Heroes.ReplayParser\Heroes.ReplayParser.ConsoleApplication\ConsoleApplication1\bin\Debug\ConsoleApplication1.exe'. Symbols loaded.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll'. Cannot find or open the PDB file.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\Users\Jeremy\Documents\GitHub\Heroes.ReplayParser\Heroes.ReplayParser.ConsoleApplication\ConsoleApplication1\bin\Debug\Heroes.ReplayParser.dll'. Symbols loaded.
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\Users\Jeremy\Documents\GitHub\Heroes.ReplayParser\Heroes.ReplayParser.ConsoleApplication\ConsoleApplication1\bin\Debug\MpqLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.NotImplementedException' in Heroes.ReplayParser.dll
'ConsoleApplication1.vshost.exe' (CLR v4.0.30319: ConsoleApplication1.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```

**Comment by JeremyHutchings** [comment]
Hi, back to it.

On the latest code for the application seems there is a lib / build error ?

Would it be possible to commit a working exe to the repo?

![build_error](https://cloud.githubusercontent.com/assets/439559/11829916/2872f30a-a355-11e5-91d9-a808600e0860.png)

**Comment by JeremyHutchings** [comment]
btw I'm sure it's 38215 now

![38215](https://cloud.githubusercontent.com/assets/439559/11829956/8dc8034e-a355-11e5-9a08-36c01932c262.png)

**Comment by barrett777** [comment]
Oh SharpZipLib is a NuGet package for the 'MpqTool' project.  If you right click the solution, you can 'Restore NuGet Packages' to restore it

If it still doesn't find the reference, you can use the NuGet Package Manager to uninstall and reinstall SharpZipLib, just for the 'MpqTool' project

**Comment by JeremyHutchings** [comment]
Looks like we're getting there. 

![replat data](https://cloud.githubusercontent.com/assets/439559/11835548/51958d22-a389-11e5-822f-ed8ac3c1a71c.png)

Is there an easy way to get the end KDA in the console app ?

**Comment by barrett777** [comment]
Glad you got it working :)

Unfortunately KDA is not yet available in the replay file (or I haven't found it)

Each player object does have a list of deaths, which I believe is accurate for all normal heroes.  It doesn't work for Lost Vikings or Uther's lv 20 resurrection talent for example

If you debug the application, you can see everything available in the 'Replay' object, and the associated Player and Unit lists

**Comment by JeremyHutchings** [comment]
:) 

http://us.battle.net/heroes/en/blog/19991410

**Comment by barrett777** [comment]
Yeah :) I'm excited!  I'll update my Github shortly after they add this

**Comment by JeremyHutchings** [comment]
>  I'm excited!

Me too ! Really looking forward to it. Any chance you could add the KDA data to the test app when you do please ?

**Comment by ghost** [comment]
I'm getting the same library/build error. @JeremyHutchings Restoring NuGet packages doesn't resolve it. Could you explain how you got it resolved?

Edit: never mind. trying it a second time seems to have solved it. strange behavior.
