### ISSUE TITLE
Replay Failure "UnexpectedResult" - 39 test replays

### ISSUE THREAD

**Issue by Zemill** [barrett777/Heroes.ReplayParser#104]
See link below for 39 replays that fail with "UnexpectedResult".  I will take a look to try and determine why its failing, but figured i'd throw this out there if anyone else wants to take a look.

https://heroesprofile.s3.us-east-2.amazonaws.com/Replays.zip

@koliva8245 This might be something you are interested in per your last comment in https://github.com/HeroesToolChest/HeroesMatchTracker/issues/13

**Comment by koliva8245** [comment]
Indeed I am. Also #57.

I looked at the first three and yes they are failing because of the missing workingSetSlotId.  I will looked through all these later and verify if setting it to the players list is workable.

**Comment by barrett777** [comment]
I remember having issues with the different player lists being in different orders sometimes.  Maybe it just affects Custom games, or games with observers.  I can't remember exactly, but be careful

**Comment by koliva8245** [comment]
replay-24366777 and replay-24368334 are battlelobby issues (that I will try to fix), replay-24379465 tracker events are "corrupted".

The rest are with the missing workingSetSlotId and setting to the the player list is acceptable.  

I would like to see a few replays that are custom games with the missing workingSetSlotId to see if setting it to the players list causes issues, but those replays are probably extremely rare.
