### ISSUE TITLE
Replay parsing exception 

### ISSUE THREAD

**Issue by Seriousnes** [barrett777/Heroes.ReplayParser#108]
If system region format is set to Turkish (either Turkey or Cyprus), the line: 
https://github.com/barrett777/Heroes.ReplayParser/blob/3b157d8f29e0eeda7ee0b9e34b5c1907b6ed3a86/Heroes.ReplayParser/DataParser.cs#L212
called from:
https://github.com/barrett777/Heroes.ReplayParser/blob/3b157d8f29e0eeda7ee0b9e34b5c1907b6ed3a86/Heroes.ReplayParser/DataParser.cs#L122
throws a "sequence contains no matching elements" exception

**Comment by koliva8245** [comment]
This is already fixed.
