### ISSUE TITLE
Scaling issue on smaller monitor

### ISSUE THREAD

**Issue by IAmScience** [barrett777/Heroes.ReplayParser#11]
Hey again,

Wasn't sure how best to report this as it is related to the actual website, not the parser.

Just refreshed the page and noticed the site now displays weird on my smaller monitor (17", 1280 x 1024 Res).  Image attached - Notice everything is being pushed to the left side.

Tested in Chrome, Firefox, and IE, all have the same problem.  Happens on all pages.  Displays normally on my other monitor at any size.

No errors in console.

Did you update the CSS?

![hotslogs scaling](https://cloud.githubusercontent.com/assets/6733768/11861946/10e4f46c-a44b-11e5-83da-eb45a6d6299b.PNG)

**Comment by barrett777** [comment]
Yeah I did update the CSS.  It's most noticeable to you because you have ad block on :)

I removed the advertisement on the left, because I changed the one on the right to support advertisements up to 300px in width (up from 160px).

For screen widths over ~1500px, I increased the content width by about 200px.

For screen widths less than 1500px, the content width is the same, but the content is on the left, with the vertical ad on the right

**Comment by IAmScience** [comment]
I dunno man, even with ad block disabled something looks a little funky.

Like the entire display (including adds) should be centered even at < 1500 px, otherwise there is so much white on the right side.

Just for comparison here is what it looks like currently, with a width of 1280 px:
![hotslogs scaling](https://cloud.githubusercontent.com/assets/6733768/11863154/234b3830-a457-11e5-9afb-47bda0589d97.PNG)

But then if the window is scaled with a width from 769 - 991 px it looks like this, totally cutting off the right-hand side ad:
![image](https://cloud.githubusercontent.com/assets/6733768/11863273/2af74a82-a458-11e5-8f58-68681473d219.png)

Then again at 992 px the content pane expands to fill, then remains the same up to width of 1049 px:
![image](https://cloud.githubusercontent.com/assets/6733768/11863319/995a2c92-a458-11e5-96f5-3b68a74c51a4.png)

Not until a window width of 1820 am I seeing it centered, which is the original view.

It just leaves the actual content pane a little small.

Just my 2-cents.

**Comment by barrett777** [comment]
Yeah I'll tweak it some more tonight to improve it some.  HOTS Logs does rely on ad revenue, so unfortunately I can't justify having empty space on the left, and then cutting off the advertisement on the right.  Most users are 1920x1080 anyway thankfully, but I'll try to find some better options for mid sized browsers.
