### ISSUE TITLE
Replay Parsing Fails on latest HoTs Patch

### ISSUE THREAD

**Issue by Zemill** [barrett777/Heroes.ReplayParser#113]
@koliva8245 

Throw exception at System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'

https://github.com/barrett777/Heroes.ReplayParser/blob/7ce8b00c5d517231715737c9c8fa58861e124604/Heroes.ReplayParser/MPQFiles/ReplayInitData.cs#L251

Looks like it is passing 15 for userID.value into the replay.ClientListByUserID array which is null at index 15

[2021-05-18 15.58.01 Warhead Junction.zip](https://github.com/barrett777/Heroes.ReplayParser/files/6504169/2021-05-18.15.58.01.Warhead.Junction.zip)

**Comment by barrett777** [comment]
I'll fix this soon

**Comment by barrett777** [comment]
Fixed in version 1.2.14 (Should be on NuGet any minute)

I was only able to test a few Quick Match games.  Let me know if it doesn't work for any other game modes.

**Comment by Zemill** [comment]
When I go to update/install the 1.2.14 update through nuget, it shows the 1.2.14 update, but it appears it is installing the 1.2.13 version.

Can you double check or am I crazy

**Comment by barrett777** [comment]
I created a little console project using the NuGet version and I think it is updated

Try compiling and then check the properties of the 'Heroes.ReplayParser.dll' in your \bin folder

![image](https://user-images.githubusercontent.com/8446995/118738939-0dbc8680-b7fd-11eb-916e-4d7822568ac8.png)

**Comment by Zemill** [comment]
Alright, I did the same thing you did and created a dummy project.  Works without issue.

Problem is, it isn't working with my AWS Lambda function....not sure why yet, its just throwing the same exception, but working on older replays, as if it isnt updating....anyway, thanks for the work on this

**Comment by barrett777** [comment]
I wasn't able to test parsing ranked modes so it may be an issue with ranked game modes
