### ISSUE TITLE
Extra Talent in Player.Talents Array

### ISSUE THREAD

**Issue by Zemill** [barrett777/Heroes.ReplayParser#116]
Attaching replay file.

I am getting an extra 8th talent for stitches in this replay.  Occurs after level 20 talent.  Thoughts?

[2cd388ff-5199-dabd-7016-bec4fa4d6745.zip](https://github.com/barrett777/Heroes.ReplayParser/files/6539123/2cd388ff-5199-dabd-7016-bec4fa4d6745.zip)

**Comment by koliva8245** [comment]
I would say its a bug.  However the "8th" talent is the correct one. 

The 7th talent has `StitchesGiftFromTheEmbalmer` for the talent name id and a talent slot id of 19. 19 is supposed to be `StitchesHookMasterHooker`. 

The 8th talent has a blank talent name id but has the correct talent slot id of 17, which is supposed to be `StitchesGiftFromTheEmbalmer`.

**Comment by barrett777** [comment]
I would guess it's related to Stitches automatically getting his long hook at level 13 now.  I can't dig deeper until later today or maybe later this week though.

**Comment by Zemill** [comment]
Thanks.  I am getting talent data up to 20 for stitches, so looks like it isn't occurring in all situations.

**Comment by barrett777** [comment]
I wonder if it only happens if a Stitches player is disconnected during the level 13 transition.  Weird things in talents used to happen if the AI picked talents for you

**Comment by barrett777** [comment]
How very strange!  Well I watched the replay and my only guess is maybe it is a bug in the game client

At 17:38, when Stitches picks his level 20 talent according to the replay: That is the exact moment Stitches is leaving the Triglav Protector (The big robot on Volskaya).

I wonder if he tried to pick his level 20 talent while exiting the robot, and it didn't work.

It doesn't show his level 20 talent picked in-game at that time, it still shows the "?" icon.

In the replay file and in the game client, Stitches picks his level 20 talent at 20:24, which is a few seconds after he dies.  I'm guessing he dies and then realizes he hasn't picked his level 20 talent yet.
