### ISSUE TITLE
Empty battletag_name and battletag_id

### ISSUE THREAD

**Issue by Zemill** [barrett777/Heroes.ReplayParser#119]
I think I am running into this issue on more than this replay, but I will submit this one.

I am getting empty battletag_name and battletag_id values for the player playing Ana in the following game

[f9b3deb2-958d-7b48-c798-815f3ca0cdd7.zip](https://github.com/barrett777/Heroes.ReplayParser/files/6909871/f9b3deb2-958d-7b48-c798-815f3ca0cdd7.zip)

**Comment by Zemill** [comment]
Correction, battletag_id equals 0

**Comment by Zemill** [comment]
ParseOptions
    {
        ShouldParseUnits = false,
        ShouldParseMouseEvents = false,
        ShouldParseDetailedBattleLobby = true,
        ShouldParseEvents = false,
        AllowPTR = false
    });

**Comment by koliva8245** [comment]
This is working as it should be. The Ana and Arthas player do not have a name nor the number part of the battle tag.

**Comment by Zemill** [comment]
Hmm you are right, they are empty in the game.  I swore I saw a method for accomplishing this on reddit at some point, both players are less than level 100....so they must've done it on purpose....

I have put in a change to my process to deal with it, so I am closing this
