### ISSUE TITLE
Map & Character hero in different languages

### ISSUE THREAD

**Issue by luchianenco** [barrett777/Heroes.ReplayParser#12]
Hi how do you manage the map & character name on hotslogs as they are different for every localization?
Do you use a a map id / character id from replay.details or any other way?
thank you

**Comment by barrett777** [comment]
I keep a dictionary of every possible hero name in different languages :)

In the replay attributes file, there is an attribute for selected Hero, and that uses a consistent 4 character string that is the same across all languages.

The only problem is this will show as 'Rand' when picking Auto Select, so you won't know what the actual Hero is when picking Auto Select.

There may be other places where you can find the selected Hero and Map in the replay file, and not have to worry about the above issues.  I haven't found it yet though
