### ISSUE TITLE
Replay version mismatch question

### ISSUE THREAD

**Issue by Zemill** [barrett777/Heroes.ReplayParser#120]
For the latest patch, the parser is returning patch version 2.54.**2**.85894, but the launcher says we are on 2.54.**3**.85894.

The heroprotocol is for  2.54.**3**.85894 as well.  Is this a problem with the parser, or did blizz mess something up?  Or am I missing something?

[3832c64f-54f5-0c4a-d347-2e55283f3c9c.zip](https://github.com/barrett777/Heroes.ReplayParser/files/7038966/3832c64f-54f5-0c4a-d347-2e55283f3c9c.zip)

**Comment by MGatner** [comment]
Interns, amirite? 😂

**Comment by barrett777** [comment]
Yeah I would guess Blizzard didn't increment a number somewhere 😄 

I'm pretty sure this library only uses the build number, `85894`, so I don't think it will affect parsing
