### ISSUE TITLE
Replays from 11/16/2021 throwing "NotImeplementedException"

### ISSUE THREAD

**Issue by Zemill** [barrett777/Heroes.ReplayParser#122]
Error getting thrown at

https://github.com/barrett777/Heroes.ReplayParser/blob/99ef9947622ca9f281ac92ea66fd530289e3288a/Heroes.ReplayParser/MPQFiles/ReplayTrackerEvents.cs#L180

[replays.zip](https://github.com/barrett777/Heroes.ReplayParser/files/7574897/replays.zip)

**Comment by barrett777** [comment]
Hmm... Blizzard hasn't made any changes for a couple months (https://github.com/Blizzard/heroprotocol)

I'll look into it sometime in the next couple days

**Comment by Zemill** [comment]
Sorry, didn't mean to imply this was new.  I've been getting sporadic reports about incomplete replays and finally found a set I was able to replicate it on

**Comment by barrett777** [comment]
Ok thanks.  I just meant usually the 'Not Implemented' cases happen when Blizzard makes changes.  I'm surprised it's coming up now.  I'll see what I can find.

**Comment by koliva8245** [comment]
It seems that you can't even load/watch the replays. After looking at the binary contents of the files, the mpq header is not in the correct format. Interesting...

**Comment by barrett777** [comment]
I can't find an easy way to salvage these replays.  Considering you can't open the replays in the game client, I'm assuming something went wrong on Blizzard's end when creating these.  I'm giving up for now unless these become more frequent

**Comment by Zemill** [comment]
Alright I appreciate you spending some time to look into it.   Odd it happened to so many of the same users replays, but maybe he has something going on

**Comment by barrett777** [comment]
In the past there have been specific issues that affect replays from the Mac version of HotS

Also some goobers try to modify their replay files once in awhile as well

**Comment by koliva8245** [comment]
I fixed this replay by rebuilding the mpq header and I see nothing "bad" about replay. No idea why the mpq archive header was built incorrectly.

[2021-11-16 19.21.14 Braxis Holdout-fixed.zip](https://github.com/barrett777/Heroes.ReplayParser/files/7577374/2021-11-16.19.21.14.Braxis.Holdout-fixed.zip)
