### ISSUE TITLE
LAN Settings - Uses Proxy Information?

### ISSUE THREAD

**Issue by veenarm** [barrett777/Heroes.ReplayParser#13]
Not sure if this can be resolved or not, or maybe a bypass option?

I started using a PROXY in my Chrome and as soon as I did hotslogs no longer connected properly - (it's in EU).

I disabled it in LAN in chrome, and instantly all files uploaded successfully.

I'm assuming it's using a http connection settings provided via chrome/default browser - any chance of a bypass proxy/connection setting?

**Comment by barrett777** [comment]
I believe it's using Internet Explorer proxy settings.  It should work through a proxy anyway though.  Can you try setting your proxy info in Internet Explorer?

"You can display the Internet Explorer Local Area Network (LAN) Settings dialog box by selecting Tools from the Internet Explorer main menu and then selecting Internet Options. Next, select the Connections tab, and click LAN Settings."

**Comment by veenarm** [comment]
Windows 10 - proxy in chrome, sets them in IE EDGE by default already.

Proxy port is 7010 - and i have some exclusions obviously, hotslogs loads fine and the website etc everything is fine, it's just nothing uploads - no replays upload just seems to stall using my proxy ( which yes works for other stuff fine ) disable proxy and all loads successfully

**Comment by barrett777** [comment]
Sorry, I'm not sure what the issue might be :( Did you set the proxy settings in Internet Explorer specifically, or just Edge?  You can still get to the old Internet Explorer by using 'Win + R' keyboard command, and 'Run' the command 'iexplore'

Perhaps the application only pulls proxy settings from Internet Explorer

**Comment by veenarm** [comment]
Yeh, not sure, it's just the upload function not working when behind the proxy, disable the proxy it works fine, proxy works for almost all other things.. It's not really a issue just thought maybe there was a way to prevent proxy settings etc.. If not its fine, i'll delete this post.

**Comment by barrett777** [comment]
Yeah sorry I'm not sure what the issue could be.  If others email me with similar problems I'll reopen and try to get to the bottom of it
