### ISSUE TITLE
Legal notice

### ISSUE THREAD

**Issue by ghost** [barrett777/Heroes.ReplayParser#14]
You're violating Blizzard's EULA by parsing 'Hero of the Storm' game replays.

http://us.blizzard.com/en-us/company/legal/eula.html

> Section 2. BLIZZARD’S OWNERSHIP.
> A. Blizzard is the owner or licensee of all right, title, and interest in and to the Battle.net Client, Battle.net, the Games, Accounts, and all of the features and components thereof. Battle.net and the Games may contain materials licensed by third-parties to Blizzard, and these third-parties may enforce their ownership rights against you in the event that you violate this Agreement. **The following components of Battle.net and/or the Games, are owned or licensed by Blizzard:**
> - **All recordings, Game replays,** or reenactments of in-game matches, battles, duels, etc.;

**Comment by barrett777** [comment]
Blizzard has supported Starcraft 2 replay file parsing for years now, even by providing their own library to do so: https://github.com/Blizzard/s2protocol

And somewhat recently, they also added a version for Heroes of the Storm replay files: https://github.com/Blizzard/heroprotocol

Of course I will honor Blizzard's feelings on this, but I've yet to receive any complaint from them

**Comment by ghost** [comment]
Oh, my fault then. It's fine when people use your tool to get other's profile information without any permission.

**Comment by barrett777** [comment]
I can remove your Profile, please email me directly at admin@hotslogs.com
