### ISSUE TITLE
Open source hotslogs.com?

### ISSUE THREAD

**Issue by adion** [barrett777/Heroes.ReplayParser#17]
@barrett777, you provide a wonderful service for the HotS community with http://hotslogs.com and some of us would love to help give back.

Would you consider open sourcing http://hotslogs.com to accept pull requests? I know there's a bunch of UX improvements I'd love to personally incorporate, but I'm sure there are things others would love to contribute too. What about your own honey do list? Have you considered publishing that and letting the community cherry pick and contribute?

Thanks a bunch!

**Comment by barrett777** [comment]
Thanks for the offer :) I may open source parts of HOTS Logs in the future.  I have been wanting to spend more time on the 'Match Details' page, and perhaps the community would be interested in improving that
