### ISSUE TITLE
How do you determine takedowns, deaths and score?

### ISSUE THREAD

**Issue by encratite** [barrett777/Heroes.ReplayParser#2]
First off, really great work on this library! I'm surprised that it has received limited attention so far.

Is it currently possible to determine the final number of takedowns, deaths and the score of a player at the end of the game using this library? I dug through the game events and tracker events and didn't manage to find anything pertaining to these stats. I wanted to use this to write a tool that permits me to track my performance with each hero (wins/losses, takedowns/deaths/score per game, etc.).

The ClientList only seems to contain win/loss and hero data.

Thanks!

**Comment by barrett777** [comment]
Hello,

I expect takedowns / deaths will be added to the replay.tracker.events, the
'PlayerStatsEvent', though currently Blizzard hasn't yet filled this in.

It may be possible to at least find deaths by checking units killed in the
replay.tracker.events, but I'm not sure.  I wasn't able to find it when I
originally looked into it, but that was awhile ago and the data may have
changed.

Thanks,
Ben

**Comment by encratite** [comment]
Yeah, that's the event I was checking out. Unfortunately, it's all zeroes right now. Ah, well, I guess I have to stick to wins and losses then.

Thanks!
