### ISSUE TITLE
Tracking deaths via replay.resumable.events

### ISSUE THREAD

**Issue by IAmScience** [barrett777/Heroes.ReplayParser#4]
Hey there,

I don't really have any experience with this sort of thing but I have looking over the replays for the few last day to see if there is any way to track player deaths.

The one thing I have noticed is that the replay.resumable.events file contains a number of references to each player equal to the number of times they have died.

I would say I have found this to be ~80% accurate, but I have noticed (from my small sample group) that these are often for a Jaina/Raynor, so I believe most differences were caused by pet deaths.  The only other factor I was able to identify when the count in the events file did not match the player death count was the player dying at the end of the match, so a death event may not have been recorded before the game was "over."

I am actually really interested in this project - But I am struggling a bit with how you are able to determine what the specific bit/byte references are, and how you are able to decode some of this gibberish.

Just wanted to share as an avid HotS player!

**Comment by barrett777** [comment]
Thanks for sharing this!  I hadn't really looked into this file as I didn't think it would have anything useful, but if it is keeping track of deaths that would be great.

It's a pain trying to figure out the structure without any help.  First I check other Starcraft 2 projects to see if someone else has looked at this file.  So far I haven't found any for this new file.  Blizzard also has a project: https://github.com/Blizzard/s2protocol.  Although they don't mention this file in particular, they have lists of data structures, and one may fit the data in this file.

Most files in the replay files refer to players by an index, so I'm surprised this file actually has their names listed (and multiple times), so this file may have a unique structure.

I've only looked at one replay file so far, but it looks like each player entry is always separated by 12 bytes, so thankfully it's consistent so far.

I'll spend some time looking into it this weekend.  Best case scenario would be finding a similar structure in Blizzard's s2protocol that might actually tell us what some of the data is, but if not I should at least be able to separate each player entry, and hopefully find some part of the data that tells us if it's an actual player death or something else.

**Comment by barrett777** [comment]
Well unfortunately I don't think this file has anything useful.  I added a file to parse this in code, and you can look through it.

Sometimes these 'resumable events' line up with deaths, but from the replay files I looked at, there were a number of deaths do not have a corresponding 'resumable event.'  Also, there are resumable events that are not associated with deaths, and the only 'data' I can find in this event does not seem to distinguish these.

My best guess is that this file may be used for people rejoining a game after disconnected, or perhaps is related to the 'resume from replay' feature in StarCraft 2 that is not (yet) available in Heroes of the Storm.

Either way, it doesn't look like anything interesting to us is in here.  Let me know if you find what the data is for though :)
