### ISSUE TITLE
Lots of missing data in Haunted Mines Replay

### ISSUE THREAD

**Issue by koliva8245** [barrett777/Heroes.ReplayParser#41]
No talents, no stats.

[Haunted Mines (4).zip](https://github.com/barrett777/Heroes.ReplayParser/files/655550/Haunted.Mines.4.zip)

**Comment by barrett777** [comment]
It looks like this parsed successfully

Talents may not be shown if they are selected by the AI while a player is disconnected

It looks like everyone has most of their talents, and their end game stats

What in particular is missing?

**Comment by koliva8245** [comment]
Found the problem, my branch wasn't up to date with yours.  It was probably commit f2976c012d2619d3fbb2f7a45d79c9a3d59e2c92 that fixed it.
