### ISSUE TITLE
ReplayHash always 0000-0000

### ISSUE THREAD

**Issue by RobertDoc** [barrett777/Heroes.ReplayParser#5]
Hi,

richTextBox1.AppendText(replay.ReplayHash.ToString());

This always returns a blank GUID - how do we uniquely identify a particular replay?

**Comment by barrett777** [comment]
Hello,

The 'RandomValue' uint is almost unique - I've only had a few duplicates in 1 million replays.

If you are only looking through a few hundred or thousand replays that may be unique enough.

For HOTS Logs, I do fill in the 'ReplayHash' Guid, using 'RandomValue' and some other parts of the replay, such as the players involved, which makes it much more unique.

**Comment by RobertDoc** [comment]
Thanks for the response!

But how do you deal with the case of two people uploading the same replay and only logging the stats once?

Thanks

**Comment by barrett777** [comment]
The 'RandomValue' and players involved will be the same for each replay, regardless of who uploads.  If you build a hash using those, it will be unique for that match, even between different players' copies of the replay.

**Comment by RobertDoc** [comment]
Ahhh, excellent, thanks!
