### ISSUE TITLE
Unable to parse replays of build 49838

### ISSUE THREAD

**Issue by mathiasgsk** [barrett777/Heroes.ReplayParser#52]
Hello!

I've tried to parse several old replays with success, but all my replays with of ReplayBuild 49838 fails due to an IndexOutOfRangeException. 

It seems that workingSetSlotID in ReplayInitData.Parse is set to 255, which is an invalid index for the array Replay.ClientListByWorkingSetSlotID of size 16.

I've attached two of the replays failing due to this error.

[Replays.zip](https://github.com/barrett777/Heroes.ReplayParser/files/1224580/Replays.zip)

**Comment by barrett777** [comment]
Thanks for finding this, I'll try to fix it within a few days

**Comment by mathiasgsk** [comment]
Thank you very much!

Further more I discovered that some heroes does not have their correct name reflected in the Unit.UnitGroupDictionary. Some of them were simply missing, but others have a totally different name as a Unit, than the characters actual name. Such as Li-Ming which as an unit is: "HeroWizard".

I've updated the list for the Dictionary with all of the heroes I found to be missing. (Possibly some duplicates when a hero's unit name differs from the actual character name, such as Li-Ming).
I've attached it here if you wish to update this part of the dictionary.
[HeroesDictionary.txt](https://github.com/barrett777/Heroes.ReplayParser/files/1227480/HeroesDictionary.txt)

**Comment by barrett777** [comment]
Ok I fixed this :)

It was interesting.  Blizzard made a change to part of the replay format in build 49582, used the new format for a couple builds, and then reverted this one section for just this patch 49838.  I'm not sure why.  I see the replays you sent were tournament matches.  Maybe they had a special tournament build?
