### ISSUE TITLE
Kills, assists and deaths as doubles

### ISSUE THREAD

**Issue by mathiasgsk** [barrett777/Heroes.ReplayParser#54]
Hello!

After using your library quite a lot, I came across replays involving Murky. Killing Murky only yields a quarter of a kill, and thus it takes four Murky kills for a complete takedown. 

Is it possible to retrieve the number of kills, assists and deaths as doubles instead of integers, as it is shown in the in-game stats-board? This would allow more detailed analysis and insight.

**Comment by barrett777** [comment]
These are unfortunately recorded in the replay file as integers, despite being shown in the in-game score screen with 0.25 kills and deaths for things

If Blizzard changes the replay format, I'll update this library and Hotslogs code

Until then, you could try to calculate it yourself by finding the Murky hero units and counting their deaths yourself, etc.  Calculating assists would be harder though.
