### ISSUE TITLE
Modifications to compile on C# 5 - forked repository

### ISSUE THREAD

**Issue by paviad** [barrett777/Heroes.ReplayParser#55]
You might want to create a 'csharp5' branch that contains the code which compiles on C# 5, I needed it, so I figured to make it available.

https://github.com/paviad/Heroes.ReplayParser/tree/csharp5

**Comment by barrett777** [comment]
Thanks for setting that up :) I'm not up for supporting it on my end, but if people ask me I'll send them to your fork
