### ISSUE TITLE
Unexpected Result on Replay

### ISSUE THREAD

**Issue by koliva8245** [barrett777/Heroes.ReplayParser#57]
Issue for replay [here](https://github.com/koliva8245/HeroesMatchTracker/issues/13) and its due to [this](https://github.com/barrett777/Heroes.ReplayParser/blob/master/Heroes.ReplayParser/MPQFiles/ReplayDetails.cs#L45).

Instead of just a `return` and causing the replay be `Unexpected Result`, can't we just do
```
replay.ClientListByWorkingSetSlotID[i] = replay.Players[i];
```

**Comment by barrett777** [comment]
That's not always the case unfortunately.  I'd rather the parse fail here than assign the wrong stats to the wrong player.
