### ISSUE TITLE
.NET Core 1.0 support

### ISSUE THREAD

**Issue by madelynnblue** [barrett777/Heroes.ReplayParser#61]
Is it possible to do something to get .NET Core 1.0 support? I tried some stuff but SharpZipLib doesn't seem to want to work with it. But I'm not a dotnet person, so I'm mostly just confused by all of this and may have missed something obvious.

I'd like this because I want to run this project on AWS Lambda, which doesn't support 2.0 yet.

**Comment by koliva8245** [comment]
Open the .netCore.sln solution in visual studio and retarget all three of
the project frameworks
ConsoleApplication - 2.0 to 1.0 Net Core
ReplayParser - 2.0 to 1.6 Net Standard
MpqTool - 2.0 to 1.6 Net Standard

Then build the solution.  However, I think that the MpqTool project (or
ReplayParser) won't build under 1.6 (I can't remember right now) and
requires 2.0 to be the minimum.  If that's the case you'll try to modify
the code to get it to work.

**Comment by barrett777** [comment]
Thanks for the info @koliva8245, I appreciate it!

**Comment by madelynnblue** [comment]
Nope, this doesn't appear to work. It complains about various things not existing and the SharpZipLib error is the same also. I guess this isn't possible.

**Comment by poma** [comment]
This commit in my fork adds support for different compression libraries, maybe some of them will work with .NET Core 1.0

https://github.com/poma/Heroes.ReplayParser/commit/ea7cb54870e9ba7f83f535a5b30785b4ece2ad44

**Comment by rogusdev** [comment]
If you go looking at the various libraries on nuget and their websites' changelogs, you can almost certainly find a version to use that will be 1.0 compatible. They all ran on 1.0 not that long ago, unless they are brand new libraries.

**Comment by koliva8245** [comment]
Here's your compatible .Net Core 1.0 (and .Net Standard 1.6) solution https://github.com/koliva8245/Heroes.ReplayParser/tree/core-1.0

The SharpZibLib that's being used is v1.0.0-alpha2 which is compatible with .Net Standard 1.6

**Comment by madelynnblue** [comment]
Woo thanks. This helps a lot.
