### ISSUE TITLE
Strange `MiscellaneousScoreResultEventDictionary` data.

### ISSUE THREAD

**Issue by wakuflair** [barrett777/Heroes.ReplayParser#66]
I parsed a replay file to extract the map objectives data, and I know it will be stored in the player's `ScoreResult` -> `MiscellaneousScoreResultEventDictionary`. 

But I found there are some strange data: 
The map  is `Volskaya Foundry`, and the replay parsed with no error.
But the `MiscellaneousScoreResultEventDictionary` data are:

~~~ json
		"MiscellaneousScoreResultEventDictionary": {
			"TeamTakedowns": 4,
			"Tier1Talent": 1,
			"Tier2Talent": 1,
			"Tier3Talent": 2,
                        ...
			"DragonNumberOfDragonCaptures": 0,
			"DragonShrinesCaptured": 0
~~~

They are  the map objectives data of the Dragon Shire??
The same thing happed again when I parsed a Hanamura replay, this time the `MinesSkullsCollected` from Haunted Mines showed up.

**Comment by koliva8245** [comment]
Can you upload/attach a replay file(s)?

**Comment by wakuflair** [comment]
[replays.zip](https://github.com/barrett777/Heroes.ReplayParser/files/1714974/replays.zip)

Replays uploaded.
The replays are from chinese region, but I don't think it will cause the issue.

**Comment by barrett777** [comment]
That is a bit odd but I wouldn't think anything of it.  It's probably something the developers forgot or didn't care to remove.  The values for these are '0' as they should be.  It's just odd that they are included on a map they don't exist on.
