### ISSUE TITLE
Game event '15' unparsable

### ISSUE THREAD

**Issue by mlynam** [barrett777/Heroes.ReplayParser#8]
Hi @barrett777,

I am attempting to parse the 'replay.game.events' file and I find that an event with integer value 15 is causing a not implemented exception from the default handler in the event switch. Do you have any idea what the structure could be for event 15?  There isn't anything in the sc2protocol repo...

**Comment by mlynam** [comment]
Replay build is 38593

**Comment by barrett777** [comment]
If there's an event that isn't documented in s2protocol, it's actually more likely that the event before this one is the problem.

What event comes before this?

**Comment by mlynam** [comment]
CCmdEvent, 3 seconds into gameplay for this particular replay.

**Comment by barrett777** [comment]
I just pushed some changes for the current build, let me know if that fixes it

**Comment by mlynam** [comment]
alright let me check it out.

**Comment by mlynam** [comment]
That did it.  Well that was awesome.  Thank you for the prompt response and your work on this.
