### ISSUE TITLE
Talent selection not available when skipping event parsing

### ISSUE THREAD

**Issue by M0shr00m** [barrett777/Heroes.ReplayParser#92]

**Comment by barrett777** [comment]
This isn't a bug, as currently we get talent selections from the events

I saw some conversation in Discord about potentially being able to get talent selections from somewhere else though?

**Comment by M0shr00m** [comment]
I may have found where to get talent selections from the Tracker events, so we wouldn't have to parse the Game Events.  It doesn't look like it includes the talent ID's like in the regular parsing though, just the talent names.  @Zemill would this work for your needs?

**Comment by Zemill** [comment]
Maybe.  I don’t use the talent ids currently.  Can you provide the code to do that and I can look into it

**Comment by Zemill** [comment]
You can close this
