### ISSUE TITLE
Document build

### ISSUE THREAD

**Issue by martijnhoekstra** [barrett777/Heroes.ReplayParser#94]
It's unclear how the build and packaging functions. Particularly, versioning is done in the GitVersion build task, but `dotnet build` doesn't function with this build task. 

I can't find out how to create a local package and how to version it.

**Comment by barrett777** [comment]
I think we've figured out most of this in the other issue: https://github.com/barrett777/Heroes.ReplayParser/issues/97

Future users can click on the build status badge to see how travis ci builds the library (https://travis-ci.com/barrett777/Heroes.ReplayParser).  I think that is good enough for now.
