### ISSUE TITLE
Publish nightly builds

### ISSUE THREAD

**Issue by martijnhoekstra** [barrett777/Heroes.ReplayParser#96]
It would be good to have nightly builds published as pre-releases packages on merge.

**Comment by barrett777** [comment]
I agree :) Let me know if anyone has a good free (or almost free) automated solution for this

**Comment by martijnhoekstra** [comment]
Travis, Circle, Github and AppVeyor have good, free, automated solutions for this.

There are probably others as well.

**Comment by barrett777** [comment]
Alright I got this set up on travis ci, thanks for the suggestions :)

At this time I'm not doing prerelease packages, but anything committed to master will get a new version number

https://travis-ci.com/barrett777/Heroes.ReplayParser
