### ISSUE TITLE
1.2.3 is breaking the API

### ISSUE THREAD

**Issue by martijnhoekstra** [barrett777/Heroes.ReplayParser#99]
v 1.2.3. is API breaking vs 1.2.2. The package seems to be packaged with semver (at least, according to the used plugins), which means the package major version should have changed to 2.0.0 per https://semver.org/

**Comment by barrett777** [comment]
Yes you are right, I'll make a 2.0.0 after development slows down.  I think there are more pieces that need to be merged at this time.

**Comment by barrett777** [comment]
I'm just going to close this now.  I goofed with the version number choice, but it's old news now.  Sorry!

**Comment by MGatner** [comment]
I forgive you!
